spring.application.name=NotificationService

server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/civicpulse_notification_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:21030-Cm-108}
spring.jpa.hibernate.ddl-auto=update

# Email config (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:ganeshilluri63@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:chuzadizfbjnexan}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
